language: python
cache: pip
python:
- '2.7'
- '3.6'
before_install:
- sudo apt-get -qq update
- sudo pip install update
install:
- pip install -r requirements.txt
script:
- python LoadGenRP.py
notifications:
  slack:
    secure: EltxqT4BrNXxkkPuFvUb3FD7DqYIgo4Emc7QU4znBNr7F4nwIYr+RQz9DSEyBsxpGW9QgvGVxTnsIugWVVKdfg0bmoMQzaAEi+PXEo/+j/K12yhBrTcsxwVPGOI7Dl9YaMMVtE41FzNUrADFaZtPNlKD8dwaX2pdnFk20YmEK2J4VihXBMI5iglvPHlH1oD9KwWcXdfVqgpIB+EdNcJ8idwlT0UoEL6fbilfqBjb8+UEiOzVF5TsgIwyL1TjqOdHk7yjq+CI4NXY3MyHg6fLaDEZ3zbTl7EGapr0G3lqEtGs3pTvF9YZctNgK2V2K7SBjLTNQXYjGWYYp/fRZiZ6dIqJxK2SXuFB5L2nTqqxWd8bLGP6kFzzWZ4QysqFWKpkLvkUIOihx4Uu0AUXwDWCDf6Z+JWWtArVpxEa2Z51DCSQlKQgyTlacqKlfegMcS7si5F+eIlVBXUKYRshT7ZgFGQq78AEAER9L1hTXXGz+ZqDDQ8gQh/gEwCh+JR6pDCbsAb6S5ShXWraVfqywedurWG4HtZxoK+XAA90Xhpx48du1xc1cBh8h0nCebT7T1B3w3PIv7bO0gvrv4juSIdebS4cQOTQM33oocHmooP/K0Xh5UA61i9okgm4gytdgdRiYpAKlvUm2C2WBkHpV7+zrWM0x4bgwrd7PD0LpUi38Bc=
